### ISSUE TITLE
Error C3861: RfcGetInt8: Identified not found

### ISSUE THREAD

**Issue by ebratz** [SAP/node-rfc#96]
Hi! 
Please can somebody help me troubleshooting this?
I'm trying to install node-rfc (napi) on:
Windows 10 x64 (System Windows_NT 10.0.17763)
Node 10.15.3
Python 2.7.11
node-gyp@5.0.2
node-pre-gyp@0.13.0
Using build tools from Visual Studio 2017 (C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe)
My SAPNWRFC SDK is correctly installed (because I have it working with PyRFC

I have downloaded today the latest sources from napi branch, and when running "npm install" I receive:

c:\users\ebratz\projetos\node-rfc-napi\src\rfcio.cc(292): error C3861: 'RfcSetInt8': identifier not found [C:\Users\ebratz\projetos\node-rfc-napi\build\sapnwrfc.vcxproj]
c:\users\ebratz\projetos\node-rfc-napi\src\rfcio.cc(671): error C3861: 'RfcGetInt8': identifier not found [C:\Users\ebratz\projetos\node-rfc-napi\build\sapnwrfc.vcxproj]

This platform sounds so common... isnt't really any build release already provided?

**Comment by bsrdjan** [comment]
Could it be that you are using the older SAP NW RFC SDK release, in which the INT8 is not supported?

You can search for RfcSetInt8 in `sapnwrfc.h`, in $SAPNWRFC_HOME\include folder and if not found, please install the latest SAP NW RFC SDK release.

**Comment by ebratz** [comment]
Thank you very much!
I was trying to build with SAP NW RFC SDK from 7.20 (Had updated it last week)
But just downloaded the 7.50 version, replaced the folder and now I'm able to build successfully!
